parameters:
  clusterName: ""
  os: ""
  dependsOn: ""
  sub: ""


jobs:
  - job: cni_k8se2e
    displayName: "CNI k8s E2E"
    dependsOn: ${{ parameters.dependsOn }}
    pool:
      name: $(BUILD_POOL_NAME_DEFAULT)
    steps:
      - task: AzureCLI@1
        inputs:
          azureSubscription: ${{ parameters.sub }}
          scriptLocation: "inlineScript"
          scriptType: "bash"
          addSpnToEnvironment: true
          inlineScript: |
            set -e
            make -C ./hack/aks set-kubeconf AZCLI=az CLUSTER=${{ parameters.clusterName }}-$(make revision)

            # sig-release provides test suite tarball(s) per k8s release. Just need to provide k8s version "v1.xx.xx"
            # pulling k8s version from AKS.
            eval k8sVersion="v"$( az aks show -g ${{ parameters.clusterName }}-$(make revision) -n ${{ parameters.clusterName }}-$(make revision) --query "currentKubernetesVersion")
            curl -L https://dl.k8s.io/$k8sVersion/kubernetes-test-linux-amd64.tar.gz -o ./kubernetes-test-linux-amd64.tar.gz

            # https://github.com/kubernetes/sig-release/blob/master/release-engineering/artifacts.md#content-of-kubernetes-test-system-archtargz-on-example-of-kubernetes-test-linux-amd64targz-directories-removed-from-list
            # explictly unzip and strip directories from ginkgo and e2e.test
            tar -xvzf kubernetes-test-linux-amd64.tar.gz --strip-components=3 kubernetes/test/bin/ginkgo kubernetes/test/bin/e2e.test

        displayName: "Setup Environment"
      - ${{ if eq(parameters.datapath, true) }}:
        - template: ../k8s-e2e/k8s-e2e-step-template.yaml
          parameters:
            testName: Datapath
            name: datapath
            clusterName: ${{ parameters.clusterName }}
            ginkgoFocus: '(.*).Networking.should|(.*).Networking.Granular|(.*)kubernetes.api'
            ginkgoSkip: 'SCTP|Disruptive|Slow|hostNetwork|kube-proxy|IPv6'
            os: ${{ parameters.os }}
            processes: 8
            attempts: 10
      - ${{ if eq(parameters.dns, true) }}:
        - template: ../k8s-e2e/k8s-e2e-step-template.yaml
          parameters:
            testName: DNS
            name: dns
            clusterName: ${{ parameters.clusterName }}
            ginkgoFocus: '\[sig-network\].DNS.should'
            ginkgoSkip: 'resolv'
            os: ${{ parameters.os }}
            processes: 8
            attempts: 3
      - ${{ if eq(parameters.portforward, true) }}:
        - template: ../k8s-e2e/k8s-e2e-step-template.yaml
          parameters:
            testName: Kubectl Portforward
            name: portforward
            clusterName: ${{ parameters.clusterName }}
            ginkgoFocus: '\[sig-cli\].Kubectl.Port'
            ginkgoSkip: ''
            os: ${{ parameters.os }}
            processes: 8
            attempts: 3
      - ${{ if eq(parameters.service, true) }}:
        - template: ../k8s-e2e/k8s-e2e-step-template.yaml
          parameters:
            testName: Service Conformance
            name: service
            clusterName: ${{ parameters.clusterName }}
            ginkgoFocus: 'Services.*\[Conformance\].*'
            ginkgoSkip: ''
            os: ${{ parameters.os }}
            processes: 8
            attempts: 3
      - ${{ if eq(parameters.hostport, true) }}:
        - template: ../k8s-e2e/k8s-e2e-step-template.yaml
          parameters:
            testName: Host Port
            name: hostport
            clusterName: ${{ parameters.clusterName }}
            ginkgoFocus: '\[sig-network\](.*)HostPort|\[sig-scheduling\](.*)hostPort'
            ginkgoSkip: 'SCTP|exists conflict' # Skip slow 5 minute test
            os: ${{ parameters.os }}
            processes: 1 # Has a short serial test
            attempts: 3
      - ${{ if and(eq(parameters.hybridWin, true), eq(parameters.os, 'windows')) }}:
        - template: ../k8s-e2e/k8s-e2e-step-template.yaml
          parameters:
            testName: Hybrid Network
            name: hybrid
            clusterName: ${{ parameters.clusterName }}
            ginkgoFocus: '\[sig-windows\].Hybrid'
            ginkgoSkip: ''
            os: ${{ parameters.os }}
            processes: 8
            attempts: 3
