pr: none
trigger: none

stages:
  - stage: setup
    displayName: Setup
    jobs:
      - job: env
        displayName: Setup
        pool:
          name: "$(BUILD_POOL_NAME_DEFAULT)"
        steps:
          - script: |
              echo "Setting up environment"
              go version
            name: "SetEnvVars"
            displayName: "Set Environment Variables"
            condition: always()
  - template: cilium/cilium-overlay-load-test-template.yaml
    parameters:
      name: cilium
      clusterType: "overlay-no-kube-proxy-up"
      clusterName: "cilium-overlay"
      nodeCount: ${LINUX_NODE_COUNT}
      vmSize: "Standard_DS4_v2"
      dependsOn: setup

  - template: singletenancy/windows-cni-load-test-template.yaml
    parameters:
      name: win_cniv1
      clusterType: "windows-cniv1-up"
      clusterName: "win-cniv1"
      nodeCount: 2
      vmSize: "Standard_B2s"
      dependsOn: setup
      windowsVMSize: ${WINDOWS_VM_SKU}
      os: windows
      cni: cniv1

#change template filepath once I have decided on the name.
  - template: singletenancy/windows-cni-load-test-template.yaml
    parameters:
      name: win_cniv1
      clusterType: "linux-cniv2-up"
      clusterName: "linuxrpv2"
      nodeCount: 2
      vmSize: "Standard_B2s"
      dependsOn: setup
      windowsVMSize: ${WINDOWS_VM_SKU}
      os: windows
      cni: cniv2
