parameters:
  dependsOn: ""
  name: ""
  clusterType: ""
  clusterName: ""
  nodeCount: ""
  vmSize: ""
  os: linux
  cni: ""
  arch: ""
  testDropgz: true

stages:
  - stage: ${{ parameters.clusterName }}
    pool:
      name: $(BUILD_POOL_NAME_DEFAULT)
    dependsOn: ${{ parameters.dependsOn }} # Setup, will add manifest stage once distros are added
    displayName: "Create Cluster - ${{ parameters.clusterName }}"
    variables:
      commitID: $[ stagedependencies.setup.env.outputs['SetEnvVars.commitID'] ]
    jobs:
      - job: create_aks_cluster_with_${{ parameters.name }}
        steps:
          - template: ../load-test-templates/create-cluster-template.yaml
            parameters:
              clusterType: ${{ parameters.clusterType }}
              clusterName: ${{ parameters.clusterName }}-$(commitID)
              nodeCount: ${{ parameters.nodeCount }}
              vmSize: ${{ parameters.vmSize }}
              region: $(LOCATION)

  - stage:  ${{ parameters.name }}
    variables:
      commitID: $[ stagedependencies.setup.env.outputs['SetEnvVars.commitID'] ]
      dropgzVersion: $[ stagedependencies.setup.env.outputs['SetEnvVars.dropgzVersion'] ]
      cnsVersion: $[ stagedependencies.setup.env.outputs['SetEnvVars.cnsVersion'] ]
    pool:
      name: $(BUILD_POOL_NAME_DEFAULT)
    dependsOn:
      - createAKSclusterWindows
      - build_images
      - setup
    displayName: "Linux CNIv2 Test"
    jobs:
      - job: integration
        displayName: "Integration Test - ${{ parameters.name }}"
        steps:
          - ${{ if contains(parameters.clusterType, overlay) }}:
            - task: AzureCLI@1
              inputs:
                azureSubscription: $(TEST_SUB_SERVICE_CONNECTION)
                scriptLocation: "inlineScript"
                scriptType: "bash"
                addSpnToEnvironment: true
                inlineScript: |
                  echo "Start Integration Tests on Overlay Cluster"
                  echo "deploy ip-masq-agent for overlay"
                  kubectl apply -f test/integration/manifests/ip-masq-agent/ip-masq-agent.yaml --validate=false
                  cd test/integration/manifests/ip-masq-agent/
                  kubectl apply -f config-custom.yaml
                  kubectl apply -f config-reconcile.yaml
                  cd ../../../..
                  kubectl get po -owide -A
                  sudo -E env "PATH=$PATH" make test-integration CNS_VERSION=$(cnsVersion) CNI_DROPGZ_VERSION=$(dropgzVersion) INSTALL_CNS=true INSTALL_AZURE_CNI_OVERLAY=true TEST_DROPGZ=${{ parameters.testDropgz }}
              name: "overlaye2e"
              displayName: "Overlay Integration"
          - ${{ if contains(parameters.clusterType, swift) }}:
            - task: AzureCLI@1
              inputs:
                azureSubscription: $(TEST_SUB_SERVICE_CONNECTION)
                scriptLocation: "inlineScript"
                scriptType: "bash"
                addSpnToEnvironment: true
                inlineScript: |
                  echo "Start Integration Tests on Swift Cluster"
                  kubectl cluster-info
                  kubectl get po -owide -A
                  sudo -E env "PATH=$PATH" make test-integration CNS_VERSION=$(cnsVersion) CNI_DROPGZ_VERSION=$(dropgzVersion) INSTALL_CNS=true INSTALL_AZURE_VNET=true TEST_DROPGZ=${{ parameters.testDropgz }}
              name: "swifte2e"
              displayName: "Swift Integration"
      - job: deploy_pods
        dependsOn: integration
        steps:
          - template: ../load-test-templates/pod-deployment-template.yaml
            parameters:
              clusterName: ${{ parameters.clusterName }}-$(commitID)
              scaleup: ${LINUX_SCALEUP} # Add to pipeline Variables
              os: ${{ parameters.os }}
              iterations: ${LINUX_ITERATIONS} # Add to pipeline Variables
          - template: ../load-test-templates/validate-state-template.yaml
            parameters:
              clusterName: ${{ parameters.clusterName }}-$(commitID)
              os: ${{ parameters.os }}
      - job: restart_nodes
        dependsOn: validate_state
        steps:
          - template: ../load-test-templates/restart-node-template.yaml
            parameters:
              clusterName: ${{ parameters.clusterName }}-$(commitID)
          - template: ../load-test-templates/validate-state-template.yaml
            parameters:
              clusterName: ${{ parameters.clusterName }}-$(commitID)
              os: ${{ parameters.os }}
              restartCase: "true"
      - template: ../k8s-e2e/k8s-e2e-job-template.yaml
        parameters:
          sub: $(TEST_SUB_SERVICE_CONNECTION)
          clusterName: ${{ parameters.clusterName }}-$(commitID)
          os: ${{ parameters.os }}
          dependsOn: restart_nodes
          datapath: true
          dns: true
          portforward: true
          service: true
          hostport: true

